version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: trivia
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
